name: moon-cms

services:
    postgres:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: ${DB_DATABASE:-moon_cms}
            POSTGRES_USER: ${DB_USERNAME:-moon}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
        volumes:
            - moon-postgres-data:/var/lib/postgresql/data
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        networks:
            - moon

    redis:
        image: redis:7-alpine
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - moon-redis-data:/data
        networks:
            - moon

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "${FORWARD_MAILHOG_PORT:-8025}:8025"
            - "1025:1025"
        networks:
            - moon

networks:
    moon:
        driver: bridge

volumes:
    moon-postgres-data:
    moon-redis-data:
